# Generated by Django 5.2.16 on 2026-07-13 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('permanent_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('race_date', models.DateField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='racing.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='racing.season')),
            ],
            options={
                'ordering': ['season', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='Racecar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racecars', to='racing.constructor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racecars', to='racing.season')),
            ],
        ),
        migrations.CreateModel(
            name='DriverEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_entries', to='racing.driver')),
                ('racecar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_entries', to='racing.racecar')),
            ],
        ),
        migrations.CreateModel(
            name='QualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('q1_time', models.CharField(blank=True, max_length=20, null=True)),
                ('q2_time', models.CharField(blank=True, max_length=20, null=True)),
                ('q3_time', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='racing.driverentry')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='racing.race')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver_entry'), name='unique_driver_qualifying_result_per_race'), models.UniqueConstraint(condition=models.Q(('position__isnull', False)), fields=('race', 'position'), name='unique_qualifying_position_per_race')],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_position', models.PositiveIntegerField(blank=True, null=True)),
                ('finishing_position', models.PositiveIntegerField(blank=True, null=True)),
                ('laps_completed', models.PositiveIntegerField(default=0)),
                ('total_time', models.CharField(blank=True, max_length=50, null=True)),
                ('fastest_lap_time', models.CharField(blank=True, max_length=20, null=True)),
                ('fastest_lap_number', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='Classified', max_length=100)),
                ('driver_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='racing.driverentry')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='racing.race')),
            ],
            options={
                'ordering': ['finishing_position'],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver_entry'), name='unique_driver_race_result_per_race'), models.UniqueConstraint(condition=models.Q(('finishing_position__isnull', False)), fields=('race', 'finishing_position'), name='unique_finishing_position_per_race')],
            },
        ),
        migrations.AddConstraint(
            model_name='racecar',
            constraint=models.UniqueConstraint(fields=('season', 'constructor'), name='unique_constructor_car_per_season'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('season', 'round_number'), name='unique_round_per_season'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('season', 'name'), name='unique_race_name_per_season'),
        ),
    ]
