# Generated by Django 5.2.16 on 2026-08-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('relocated', 'Relocated')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='status_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
