# Generated by Django 5.2.16 on 2026-08-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_race_status_race_status_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintQualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('q1_time', models.CharField(blank=True, max_length=20, null=True)),
                ('q2_time', models.CharField(blank=True, max_length=20, null=True)),
                ('q3_time', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_qualifying_results', to='racing.driverentry')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_qualifying_results', to='racing.race')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver_entry'), name='unique_sprint_qualifying_result')],
            },
        ),
        migrations.CreateModel(
            name='SprintResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_position', models.PositiveIntegerField(blank=True, null=True)),
                ('finishing_position', models.PositiveIntegerField(blank=True, null=True)),
                ('laps_completed', models.PositiveIntegerField(default=0)),
                ('total_time', models.CharField(blank=True, max_length=30, null=True)),
                ('fastest_lap_time', models.CharField(blank=True, max_length=20, null=True)),
                ('fastest_lap_number', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('status', models.CharField(default='Classified', max_length=100)),
                ('driver_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to='racing.driverentry')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to='racing.race')),
            ],
            options={
                'ordering': ['finishing_position'],
                'constraints': [models.UniqueConstraint(fields=('race', 'driver_entry'), name='unique_sprint_result')],
            },
        ),
    ]
