# Generated by Django 5.2.16 on 2026-08-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0003_sprintqualifyingresult_sprintresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverentry',
            name='end_round',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverentry',
            name='start_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='driverentry',
            constraint=models.UniqueConstraint(fields=('racecar', 'driver', 'start_round'), name='unique_driver_entry_stint'),
        ),
        migrations.AddConstraint(
            model_name='driverentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_round__isnull', True), ('end_round__gte', models.F('start_round')), _connector='OR'), name='driver_entry_valid_round_range'),
        ),
    ]
